#!/usr/bin/env bash

alias grep="grep -oP -m1"
readonly GREEN="\e[32m"
readonly RED="\e[31m"
readonly YELLOW="\e[1;33m"
readonly RESET="\e[0m"
declare -A colors
colors["A"]="$RED"
colors["B"]="$YELLOW"
colors["C"]="$GREEN"
colors["completed"]=""
prog=$(basename $0)
taskdir="$HOME/todo/tasks"
tododir="$HOME/todo"
donedir="$HOME/todo/done"
deletedir="$HOME/todo/deleted"
mkdir -p $tododir $taskdir $deletedir $donedir

dieError() {
    1>&2 printf '%s: %s\n' "$prog" "$1"
    exit 1
}
usage() {
    cat<<EOF
$prog - Handles todos

Commands:
    add title - add a task with title
    del|delete x - delete task with id x in list
    list - Lists all open tasks
    list all - Lists all tasks
    archive x - archive task with id x in list
    archive all - Archives all completed todos

Not implemented yet:
    pri|prioritize x [a-zA-Z]
    show x
    edit x
EOF
    exit 1
}

# from https://gist.github.com/briantjacobs/7753bf850ca5e39be409
parse_yaml() {
    local prefix=$2
    local s
    local w
    local fs
    s='[[:space:]]*'
    w='[a-zA-Z0-9_]*'
    fs="$(echo @|tr @ '\034')"
    sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
    awk -F"$fs" '{
    indent = length($1)/2;
    vname[indent] = $2;
    for (i in vname) {if (i > indent) {delete vname[i]}}
        if (length($3) > 0) {
            vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
            printf("local %s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, $3);
        }
    }' | sed 's/_=/+=/g'
}

print_file() {
    # parse_yaml <(sed -n '/---/, /---/{ /---/!p }' "$1")
    eval $(parse_yaml <(sed -n '/---/, /---/{ /---/!p }' "$1"))

    tagstr=$(for t in ${tags_[@]}; do printf ' +%s' "$t"; done; printf '\n')
    contextstr=$(for t in ${contexts_[@]}; do printf ' @%s' "$t"; done; printf '\n')
    [ ! -z $pri ] && color=${colors[$pri]}

    if [ ! -z "$completed" ];
    then
        color="${colors["completed"]}"
    fi

    [ ! -z $pri ] && printf '%b' $color
    printf '%i ' "$tasks"
    [ ! -z $pri ] && printf '%s ' "($pri)"
    printf '%s' "$title"
    printf '%b%s%s%b\n' "$YELLOW" "$tagstr" "$contextstr" "$RESET"

    ((processed = processed+1))
}

archive() {
    eval $(parse_yaml <(sed -n '/---/, /---/{ /---/!p }' "$1"))

    # Don't print completed tasks
    [ -z "$completed" ] && dieError "cannot archive task: Not completed"

    echo "Archiving $(realpath --relative-to=. "$1")"
    mv "$1" "$HOME/todo/done/"
    ((processed = processed+1))
}

createTask () {
    task="${@}"
    title="$(echo "$task" | sed "s/([a-zA-Z]) //")"
    pri="$(echo "$task" | grep -Po "\(\K[a-zA-Z]")"
    fname=$(echo $title | sed 's/ /-/g' | grep "\(([a-zA-Z]\)\?[a-zA-Z\-]")
    destfile="$taskdir/$fname"
    [ -f $destfile ] && dieError "cannot create task '$fname': Task exists"
    cat<<EOF > "$taskdir/$fname"
---
title: $title
date: $(date +%Y-%m-%d)
pri:$pri
tags:
completed:
---
EOF
}

listTasks () {
    tasks=0
    processed=0
    listdir="$taskdir"/*
    [ "$1" == "all" ] && listdir="$tododir"/**/*
    for f in $listdir
    do
        [ ! -e ${f} ] && continue;
        ((tasks = tasks+1))
        print_file ${f}
    done
    
    echo '--'
    printf 'TODO: %s of %s tasks shown\n' $processed $tasks
}


if [[ "$1" == "add" ]]
then
    createTask "${@:2}"
    exit 0
fi

if [[ "$1" == "list" ]]
then
    listTasks $@
    exit 0
fi

if [[ "$1" == "del" ]] || [[ "$" == "delete" ]]
then
    tasks=0
    processed=0
    listdir="$taskdir"/*
    for f in $listdir
    do
        [ ! -e ${f} ] && continue;
        ((tasks = tasks+1))
        if [[ " ${@:2} " =~ " $tasks " ]]
        then
            mv ${f} "$deletedir"/
            printf '%s deleted\n' ${f}
        else
            usage
        fi;
    done
    exit 0
fi
if [[ "$1" == "archive" ]]
then
    tasks=0
    processed=0
    listdir="$taskdir"/*
    for f in $listdir
    do
        [ ! -e ${f} ] && continue;
        ((tasks = tasks+1))
        if [ "$2" == "all" ] || [[ " ${@:2} " =~ " $tasks " ]]
        then
            archive ${f}
        else
            usage
        fi
    done
    printf '%s of %s tasks archived\n' $processed $tasks
    exit 0
fi

usage
